let cocktailArr = [{
    name: "Old Fashioned",
    spirit: "Whiskey",
    des: "Despite its name this drink doesn’ t risk losing popularity. It might even have been the very first alcoholic drink called‘ cocktail’.While some say that it was named by the barman at Pendennis Club, and then a club’ s member introduced it at the Waldorf Astoria hotel bar in New York, others date the drink rumour has it that this mix was served even before Pendennis Club was founded.It’ s served in a thick and short Tumbler called clearly Old Fashioned glass",
    ingre: "<ul><li>1/3 Bourbon </li><liv> Scotch or Rye Whisky(40 ml)</li> <li>1 sugar cube </li><li>½tsp Angostura </li><li> A few drops of soda </li><li> 2 maraschino cherries</li></ul>",
    instr: "<ul><li>Method: mix;</li><li> Glass: old fashioned; </li><li>Ice: cubes;</li><li>Garnish: lemon slice,lemon rind,2 maraschino cherries </li><li> One dash Angostura one dash Curacao Piece of cut loaf sugar Dissolve in two spoonfuls of water liquor</li></ul>",
    image: "img/oldfashioned.jpg"
  },
  {
    name: "Martini",
    spirit: "Vodka",
    des: "One of the cocktails that actually made it onto the big screen as James Bond’s favorite drink. And, of course, it was always taken \"shaken, not stirred\". The Vodka Martini substitutes vodka for the traditional gin in a basic martini",
    ingre: "<ul><li>1 1/3 oz Finlandia Vodka (40 ml) </li><li>⅔ oz dry vermouth (20 ml) </li><li>1 olive </li><ul>",
    instr: "Mix the drink in a ice-filled shaker. Shake well. Strain into a martini glass. Serve with an olive",
    image: "img/martini.jpg"
  },
  {
    name: "Dirty Martini",
    spirit: "Gin",
    des: "Just like the original, this variation has become a real classic. The name ‘dirty’ comes from the olive brine which adds an extra olive flavoring compared to the straight Martini. However, bear in mind that you can easily ruin the drink if you use too much olive brine ",
    ingre: "<ul> <li>2 ½ oz gin (75 ml)</li><li>½ oz dry vermouth (15 ml)</li><li>Olive brine to taste olive for garnish</li></ul>",
    instr: "<ul><li>Method: pouring;</li><li>Glass: cocktail;</li><li>Ice: cubes;</li><li>Garnish: green olives; </li></ul>Mix all ingredients in a chilled cocktail shaker and pour into cocktail drinking glasses. Add a green olive to create a great drink with little effort!",
    image: "img/dirty_martini.jpg",
  },
  {
    name: "Margarita",
    spirit: "Tequila",
    des: "When it comes to who invented this immensely popular cocktail and when things get ambiguous (a lot). Since there is more than one story, we are going to give you two of them: The most spread version of its origin is probably the one going back to the late 1930’s at Rancho La Gloria, a restaurant near Rosarito Beach, Mexico, just across the border from San Diego. Supposedly, the owner, Danny Herrera, invented the drink for a showgirl named Marjorie King who was allergic to any kind of alcohol except tequila. America’s favorite cocktail even has its own celebration day on February 22nd",
    ingre: "<ul><li>2 ⅓ oz tequila (70 ml)</li><li>1 ⅓ oz Triple Sec (Curacao/Cointreau)(40 ml)</li><li>1 oz lemon/lime juice (30 ml)</li></ul>",
    instr: "This is the official 7:4:3 proportion of International Bartenders Association; however, the most popular ones are 2:1:1, 3:2:1, 3:1:1 and 1:1:1. Rim glass with salt. Add all the ingredients into a cocktail shaker with ice. Shake well. Strain into a cocktail glass (martini glass), rimmed with salt. Garnish with a lime wedge.",
    image: "img/margarita.jpg",
  },
  {
    name: "Mojito",
    spirit: "Rum",
    des: "The Mojito drink was Hemingway’s second favorite cocktail, after Daiquiri. Although its origins are still unclear, speculations say that Cuba is the parent country. One version of the story explains that Mojito’s first recipe was created in the 16th century for Sir Francis Drake, by using aguardiente - rum’’s predecessor. Another version says that Mojito’s origins belong to the African slaves working on Cuba’s ",
    ingre: "<ul><li>1 ⅓ oz white rum(40 ml)</li><li>1 oz lime juice(30 ml)</li><li>2 tsp powdered sugar</li><li>Soda</li><li>Fresh mint leaves</li><li>Lime slice</li></ul>",
    instr: " Thoroughly mix mint, sugar and lime juice in a tall glass.Add rum and soda.Garnish with mint leaves and a slice of lime.Serve with a straw.",
    image: "img/mojito.jpg",
  },
  {
    name: "Daiquiri",
    spirit: "Rum",
    des: "Daiquiri is the name of a beach near Santiago de Cuba but also the name of a family of cocktails whose main ingredients are rum, lime juice, and sugar. The Daiquiri is believed to have been developed in the late 1800’s in Cuba, possibly as a medicinal treatment. There are many variations for the recipe but the classic Daiquiri is amazingly simple and the three ingredients should be balanced in the glass",
    ingre: "<ul><li>1 ⅓ oz white rum(40 ml)</li><li>1 ⅓ oz lime juice(40 ml) </li><li>⅙oz sugar syrup(5 ml)</li></ul>",
    instr: "Pour the ingredients into a cocktail shaker with ice cubes. Shake well. Strain into a chilled cocktail glass.",
    image: "img/daiquiri.jpg",
  },
  {
    name: "Whiskey Sour",
    spirit: "Whiskey",
    des: "Back in 1852, Elliot Stubb created the recipe by mixing whisky with lime juice and sugar. The end result was a delicious drink, which eventually became so popular that British sailors took it to the island ",
    ingre: "<ul></li>1 ½ oz bourbon(45 ml)</li><li>1 oz lime juice(30 ml) </li>½oz sugar syrup(15 ml)</li><li>(optional) a few dashes of raw egg white </li></ul>",
    instr: "<ul><li>Combine bourbon, lemon juice, and simple syrup in a cocktail shaker.</li><li>Fill shaker with ice, cover, and shake vigorously until outside of shaker is very cold, about 20 seconds.</li><li>Strain cocktail through a Hawthorne strainer or a slotted spoon into an old-fashioned or rocks glass filled with ice. Garnish with orange wheel and cherry.</li></ul>",
    image: "img/whiskey_sour.jpg"
  },
  {
    name: "Bloody Mary",
    spirit: "Vodka",
    des: "This cocktail needs no introduction… However, here’s some trivia: It has been called \"the world’ s most complex cocktail\" or a \"savage combination of tomato juice and vodka\". Whichever you would choose, the popularity of Bloody Maru is definitely untouchable. According to some its origins go back to early 1920s when a bartender named Fernand \"Pete\" Petiot invented a rudimentary version of the mixture while working at the famed Harry’s New York Bar in Paris. Others claim this unusual combination goes back even further to the rule of ruthless Queen Mary I of England in the mid-1550s.",
    ingre: "<ul><li> 1 ⅓ oz vodka(40 ml)</li><li>30⅓ oz tomato juice(100 ml)</li><li>½tsp lemon juice </li><li>¼tsp Worchestershire sauce</li><li>4 dashes of Tabaso sauce </li><li>A pinch of celery salt </li><li>A pinch of ground black pepper</li><li>Stalk celery</li><ul>",
    instr: "Build the drinks in a highball glass over ice cubes. Mix well. Add the seasonings to taste. Garnish with the lemon and/or lime wedge and celery stalk",
    image: "img/bloody_mary.jpg",
  },
  {
    name: "Martinez",
    spirit: "Gin",
    des: "The origin of this cocktail, like many others, is uncertain. While some say a guy named Martinez baptized it after combining gin and vermouth, according to others it was invented by Professor Jerry Thomas for a patron traveling to Martinez, California. Even its recipe splits its fans- some use dry vermouth and/or Cointreau (instead of maraschino). however , on one thing most of opinions agree- this cocktail was the one to inspire the universal Martini",
    ingre: "<ul><li>2 oz sweet white vermouth(60 ml) </li><li>1 oz gin(30 ml) </li><li>5 - 6 dashes of Angostura Bitters </li><li>¼spoon Maraschino liqueur </li></ul>",
    instr: "Combine all ingredients in a shaker with ice. Stir well. Strain into a cocktail glass. ",
    image: "img/martinez.jpg",
  },
  {
    name: "Negroni",
    spirit: "Gin",
    des: "Another classic drink which uses Campari as the key ingredient to this great short gin cocktail that makes one of the most popular pre-dinners. Most common belief is that this cocktail was created and named for Count Cammillo Negroni in the 1920’s when he ordered an Americano with gin at Cafe Casoni in Florence, Italy  ",
    ingre: "<ul><li>1 oz sweet vermouth(30 ml) </li><li>1 oz Campari(30 ml) </li><li>1 oz gin(30 ml) </li><li>Orange slice or twist for garnish </li></ul>",
    instr: "<ul><li>Method: Mix</li><li>Glass: Old Fashioned</li><li>Ice: Cubes</li><li>Garnish: Orange slice / lemon rind</li></ul>Pour the ingredients into an old fashioned glass with ice cubes.Stir well.Garnish with an orange slice or lemon rind",
    image: "img/negroni.jpg",
  },
  {
    name: "Aviation",
    spirit: "Gin",
    des: "The origins of Aviation Cocktail remain (unlike the drink itself) rather murky. Some sources, such as David Wondrich’s \"Imbibe!\", tell it was first printed in a 1916 book by Hugo Ensslin called \"Recipes for Mixed Drinks\". Aviation has established itself as a popular mixture over the years and recently was dubbed one of the classics for aficionado imbibers.",
    ingre: "<ul><li>2 oz gin(60 ml)</li><li>1/4 oz maraschino liqueur</li><li>1/4 ounce ​crème de violette liqueur</li><li> 1/2 ounce freshly squeezed lemon juice</li><li>Flamed lemon peel, for garnish</li></ul>",
    instr: "Stir the ingredients into the shaker along with ice. Strain the mix into an Old Fashioned glass with ice. Garnish the drink with half-slice of orange and a maraschino cherry. You can make a Boston Sour by adding just a pinch of raw egg white ",
    image: "img/aviation.jpg",
  },
  {
    name: "Blue Lagoon",
    spirit: "Vodka",
    des: "Blue Lagoon is an excellent summer cocktail made with Blue Curacao. Some say it was invented around 1980 by a bartender inspired by ‘The Blue Lagoon’ movie. Others claim it was created in the 1960’s by Andy MacElhone, son of the famous Harry, of Harry’s Bar in Paris.",
    ingre: "<ul><li>1 oz vodka(30 ml)</li><li>1 oz Blue Curacao(30 ml) </li><li>4 oz lemonade(120 ml) </li></ul>",
    instr: "<ul><li>Shake vodka and Blue Curacao with ice.</li><li>Pour into the glass.</li><li>Add lemonade</li></ul>",
    image: "img/blue_lagoon.jpg",
  },
  {
    name: "Pina Colada",
    spirit: "Rum",
    des: "A very popular drink of Caribbean cruisers invented in 1954 by Ramon \"monchito\" Marrero, a bartender at the Caribe Hilton Hotel in San Juan, Puerto Rico. He wanted to capture all the flavors of Puerto Rico and offer them in a single mixture. After experimenting for three months he was satisfied with the pina colada (translated as ‘strained pineapple’).",
    ingre: "<ul><li>1 oz white rum(30 ml) </li><li>1 oz coconut cream(30 ml) </li><li>3 oz pineapple juice(90 ml)</li></ul>",
    instr: "Put all of the ingredients into a blender with two cups of crushed ice. Blend until the mixture becomes thick and creamy. Strain the mix into a glass, and serve with a straw and a pineapple wedge or maraschino cherry.<br> <strong>Suggestion:</strong> As an alternative for the coconut cream you can use condensed milk or coconut milk.",
    image: "img/pinacolada.jpg",
  },
  {
    name: "Moscow Mule",
    spirit: "Vodka",
    des: "In 1941, John Martin, president of Heublein together with Jack Morgan, owner of the Cock’n’Bull bar in Hollywood concocted Morgan’s ginger beer with Smirnoff and lime and gave it the name which has made it popular ever since. They ordered specially engraved copper mugs and Martin started to market the mix in bars and clubs around the country. ‘Vodka-mania’ that took by storm the 50’s was in its early beginnings. ",
    ingre: "<ul><li>1 ½ oz vodka(45 ml)</li><li>3 oz ginger beer(90 ml) </li><li>¼oz lime juice(8 ml)</li><li>1 tsp sugar syrup</li><li>mint sprig</li><li>1 slice of lime </li></ul>",
    instr: "Pour vodka over ice in a copper mug (as tradition calls for) or cocktail glass. Add sugar syrup and lime juice. Top with ginger beer and stir. Use mint sprig and lime slice to garnish. ",
    image: "img/mosco_mule.jpg",
  },
  {
    name: "Long Island Iced Tea",
    spirit: "Triple Sec",
    des: "This playful long drink contains approximately 30% alcohol, so don’t let yourself be fooled by its name. However, there are variants of this drink that are less \"aggressive\", but be careful not to ask the bartender for the extra-long version. The original recipe was supposedly invented by Robert (Rosebud) Butt back in the ‘70s, when he was working as a bartender at the Oak Beach Inn(NY, Long Island). ",
    ingre: "<ul><li>½ oz gin(15 ml) </li><li>½oz vodka(15 ml) </li><li>½oz tequila(15 ml) </li><li>½oz white rum(15 ml) </li><li>½oz triple sec(15 ml) </li><li>⅔oz lemon juice(20 ml) </li><li>1 oz sugar syrup(30 ml) </li><li>1 tsp cola </li></ul>",
    instr: "Stir the ingredients in a Collins glass, add ice cubes and serve ",
    image: "img/longislandicedtea.jpeg",
  },
  {
    name: "Manhattan",
    spirit: "Whiskey",
    des: "It seems the recipe has been invented in the Manhattan Club in New York, especially for a banquet given by Jennie Jerome, that is Lady Randolph Churchill, the mother of Winston Churchill. The success of the banquet also made the drink very popular ",
    ingre: "<ul><li>⅔ oz sweet vermouth(20 ml) </li><li>1 ⅔ oz bourbon whiskey(50 ml) </li><li>1 dash Angostura bitters </li><li>1 maraschino cherry </li><li>1 twist orange peel </li></ul>",
    instr: "<ul><li>Method: Shake;</li><li>Glass: Collins;</li><li>Ice: Cubes;</li><li>Garnish: Maraschino cherries.</li><li>Combine the bourbon whiskey,vermouth, and bitters with 3 ice cubes in a mixing glass.Stir gently without bruising the spirits or clouding the drink.Put the cherry in a chilled cocktail glass and strain the whiskey mixture over it.Rub the cut edge of the orange peel over the rim of the glass and twist it over the drink to release the oils but don’ t drop it in .Then relax and just enjoy!</li></ul>",
    image: "img/manhattan.jpg",
  },
  {
    name: "Sazerac",
    spirit: "Whiskey",
    des: "New Orleans’ undisputed protagonist when it comes to cocktails. Allegedly, this mixture was created by a Creole apothecary named Antoine Amadie Peychaud who moved to New Orleans from the West Indies and set up shop in the French Quarter in the first decades of the 19th Century. Around 1830s (or 1850s according to other sources) a toddy he prepared for some friends made him famous. It consisted of French brandy combined with his secret blen of bitters, a splash of water and a bit of sugar. As of 2008 it is the Official Cocktail of the City of the New Orleans.",
    ingre: "<ul><li>2 ½ oz Rye Whiskey(75 ml) </li><li>¼tsp Bitter Peychaud </li><li>5 - 6 Angostura Bitters </li><li>Absinth </li><li>1 sugar cube </li><li>Lemon peel</li></ul>",
    instr: "Use an Old Fashion glass to dip the sugar cube in a few dashes of water. Add a few ice cubes. Pour the drinks and stir. Wet the inside of another Old Fashioned glass with just a little bit of absinth (remove the surplus afterwards) then pour the content from the first glass into the second one. Squeeze over the mixture a few drops from the lemon peel.",
    image: "img/sazerac.jpg",
  },
  {
    name: "Presbyterian",
    spirit: "Whiskey",
    des: "As a young bartender I would occasionally answer the call for a, “Bourbon Press”. This is short for the Presbyterian Cocktail, a drink from the old guard that is ridiculously simple in execution but sublime in its expression. How a cocktail takes on the name of a religion is somewhat a mystery. Some accounts suggest that it was originally a temperance cocktail that quietly received a dosing of Whiskey non-the-wiser to the congregation. Traditionally it is a blend of some sort of Whiskey with equal parts of ginger ale and club soda. The great thing about this drink is it works with a base of Scotch, Rye, Bourbon, Brandy, and Rum. This is the perfect highball for those who do not like too much sugar with the 50% dilution of club soda to the ginger-ale effectively balancing the cocktail and drying it out a bit.",
    ingre: "<ul><li>½ oz liqueur Maraschino(15 ml)</li><li>½oz lemon juice(15 ml)</li><li>1 or 2 maraschino cherries</li></ul>",
    instr: "Pour the ingredients into a cocktail shaker filled with ice. Shake well. Strain into a chilled cocktail glass. Garnish with a maraschino cherry",
    image: "img/presbyterian.jpg",
  },
  {
    name: "Ramos Gin Fizz",
    spirit: "Gin",
    des: "Henry C.Ramos came up with the recipe at the end of the 1880s. It’s a very demanding cocktail mix that requires patience and plenty of ingredients. But it’s all worth it for the fine cream, the freshness given by the lemon juice, and the consistency provided by the albumen. To top that, there’s also the sugar that brings a pinch of calm to the whole mix, the orange flowers that add a bit of mystery, and, of course, the gin ",
    ingre: "<ul><li>2 oz gon(60 ml) </li><li>1 oz sweet fat cream(30 ml) </li><li>1 egg whites </li><li>½oz lemon juice(15 ml) </li><li>½pz lime juice(15 ml) </li><li>2 tsp powdered sugar </li><li>2 - 3 dashes of orange blossom water </li><li>soda </li><li>orange slice </li></ul>",
    instr: "Mix the ingredients together (except for the soda) in a shaker, along with crushed ice. Thoroughly shake the mix for at least 1 minute, preferably 2 minutes. Strain into a tall glass and add soda ",
    image: "img/ramod_gin_fizz.jpg",
  },
  {
    name: "White Lady ",
    spirit: "Gin",
    des: "This \" lady \" has caught the attention of some many celebrities that it has become one itself. It is said that \"she\" was favored by Laurel and Hardy, the two brilliant minds who entertained millions by playing\"Stan and Bran\". The drink’s origin is still disputed by two famous bars: Harry’s New York Bar (Paris) and The Savoy’s. The drink is also known as Chelsea Sidecar, because it;s simply a Sidecar where cognac is replaced by gin. There’s also a version that combines egg white with sugar and whip cream.  ",
    ingre: "<ul><li> 2 oz gin(60 ml) </li><li> 1 oz cointreau(30 ml) </li><li> 1 oz lemon juice(30 ml) </li><li> Lemon peel </li></ul>",
    instr: "Shake the ingredients well with cracked ice. Strain into a chilled cocktail glass. Garnish with lime peel",
    image: "img/white_lady.jpg",
  },
  {
    name: "French 75",
    spirit: "Gin",
    des: "This is a delightful champagne based cocktail created in 1915 at the Paris landmark Henry’s New York Bar, by barman Hery MacElhone. It takes its name from the 75 millimeter field gun used in WW I ",
    ingre: "<ul><li>5 oz cold champagne(150 ml) </li><li>1 oz gin(30 ml) </li><li>1 oz lemon juice(30 ml) </li><li>1 tsp powder sugar </li><li>5 - 6 ice cubes </li></ul>",
    instr: "<ul><li>Method: Mix</li><li>Glass: Collins</li><li>Ice: Cubes</li><li>Garnish: Lemon slice</li><li>Pour the sugar into a tall glass, add the lemon juice and the gin.Stir well.Add the ice cubes and fill up with champagne.Garnish with a slice of lemon or / and a cherry</li></ul>.",
    image: "img/french_75.jpg",
  },
  {
    name: "Brandy Alexander ",
    spirit: "Brandy",
    des: "Originally, this cocktail used gin as the main ingredient but then someone thought brandy would be a better choice, the drink quickly conquered new fans. Popular throughout the 0th Century the Brandy version of cocktail has a distinct warmth and smoothness and accompanies quite pleasantly chocolate desserts",
    ingre: "<ul><li>1 oz cream(30 ml) </li><li>1 oz dark creme de cacao(30 ml) </li><li>1 oz brandy(30 ml)</li><li>Ground nutmeg for garnish.",
    instr: "<ul><li>Method: Shaker</li><li>Glass: Cocktail</li><li>Ice: Cubes</li><li>Garnish: Ground nutmeg</li><li>Pour the ingredients into a cocktail shaker with ice cubes and shake well.Strain into a chilled cocktail glass.Garnish with a dusting of nutmeg.</li></ul>",
    image: "img/brandy_alexander.jpg",
  },
  {
    name: "Pink Lady ",
    spirit: "Gin",
    des: "Originally, this ‘lady’ showed up in 1912, and named after a Broadway show. There are many \" ladies \" different in colour and flavour from white to blue to meet a feminine demand in taste. This one, however, does not fall under the same category, for it is dry and poorly aromatic. That is to say that it’s quite deceitful in appearance and dangerous once tasted. Just like some of its non- liquid correspondents  ",
    ingre: "<ul><li>1 ½ oz gin(45 ml) </li><li>1 tsp Grenadine </li><li>1 tsp cream </li><li>1 egg whites </li></ul>",
    instr: " Pour the ingredients into a cocktail shaker with ice cubes. Shake vigorously. Strain into a chilled cocktail glass. Garnish with a maraschino cherry.",
    image: "img/pink_lady.jpg",
  },
  {
    name: "Godmother",
    spirit: "Vodka",
    des: "Probably the easiest to make cocktail. The mix also known as Tawny Russian is the softer variation of the more famous Godfather but without the Scotch and with Vodka ",
    ingre: "<ul><li>1 oz Vodka(30 ml) </li><li>1 oz Amaretto(30 ml) </li></ul>",
    instr: "<ul><li>Pour the ingredients in an old - fashioned glass with ice cubes</li><li>Stir well</li><li>Serve and enjoy.</li></ul>",
    image: "img/god_mother.jpg",
  },
  {
    name: "Godfather",
    spirit: "Amaretto",
    des: "Obviously, it’s rather hard not to think of Francis Ford Coppola's trilogy when hearing about this gangsterish cocktail. ",
    spirit: "Whiskey",
    ingre: "<ul><li>1 ½ oz Scotch Whiskey(45 ml) </li><li>½oz Amaretto </li></ul>",
    instr: "<ul><li>Method: mix </li><li>Glass: old - fashioned </li><li>Ice: cubes </li><li>Fill a rocks or old fashioned glass with ice, Pour scotch and amaretto and then </li></ul>",
    image: "img/god_father.jpg",
  },
  {
    name: "Brandy Eggnog",
    spirit: "Brandy",
    des: "This is like the spoiled baby of the drinks which can be both alcoholic and non alcoholic",
    ingre: "<ul><li>1 ⅔ oz milk(50 ml) </li><li>1⅓ oz brandy(40 ml) </li><li>1 - 2 tsp sugar syrup </li><li>1 egg yolk </li></ul>",
    instr: "<ul><li>Method: shaker </li><li>Glass: cocktail </li><li>Ice: cubes </li><li>Garnish: nucsoara macinata </li></ul>",
    image: "img/brandy_eggnog.jpg",
  },
];